### ISSUE TITLE
Re-export broken in 2.8

### ISSUE THREAD

**Issue by rmitton** [TiliSleepStealer/blender-addon-fbx-bundle#1]
Hi,
The Re-Export button doesn't function properly, giving the following traceback:

```
Traceback (most recent call last):  
  File "C:\Users\kayamon\AppData\Roaming\Blender Foundation\Blender\2.80\scripts
\addons\FBXBundleExporter\op_file_export_recent.py", line 39, in execute  
    export_recent(self)
  File "C:\Users\kayamon\AppData\Roaming\Blender Foundation\Blender\2.80\scripts
\addons\FBXBundleExporter\op_file_export_recent.py", line 68, in export_recent  
    for i in range(len(obj.layers)):  
AttributeError: 'Object' object has no attribute 'layers'
```

This is using the latest 1.51 release.

It's not a big problem as you can always just re-select everything and do a fresh export.

**Comment by TiliSleepStealer** [comment]
Thanks for taking the time to post this issue. I will try to fix it this week.

**Comment by TiliSleepStealer** [comment]
Looks like we need to do some changes as described here: https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Python_API/Scene_and_Object_API

**Comment by TiliSleepStealer** [comment]
@rmitton Have a try with this build: https://github.com/TiliSleepStealer/blender-addon-fbx-bundle/releases/tag/release_1.5.1.1

**Comment by rmitton** [comment]
That's fixed it, thank you so much!

(and many thanks for making this add-on work with 2.8, it's absolutely indispensable!)
